export const ADMIN_GET_BOOKINGS_REQUEST = "ADMIN_GET_BOOKINGS_REQUEST";
export const ADMIN_GET_BOOKINGS_SUCCESS = "ADMIN_GET_BOOKINGS_SUCCESS";
export const ADMIN_GET_BOOKINGS_FAILURE = "ADMIN_GET_BOOKINGS_FAILURE";

export const ADMIN_VERIFY_BOOKING_REQUEST = "ADMIN_VERIFY_BOOKING_REQUEST";
export const ADMIN_VERIFY_BOOKING_SUCCESS = "ADMIN_VERIFY_BOOKING_SUCCESS";
export const ADMIN_VERIFY_BOOKING_FAILURE = "ADMIN_VERIFY_BOOKING_FAILURE";

export const ADMIN_REJECT_BOOKING_REQUEST = "ADMIN_REJECT_BOOKING_REQUEST";
export const ADMIN_REJECT_BOOKING_SUCCESS = "ADMIN_REJECT_BOOKING_SUCCESS";
export const ADMIN_REJECT_BOOKING_FAILURE = "ADMIN_REJECT_BOOKING_FAILURE";


export const CLEAR_ADMIN_BOOKING_MESSAGE = "CLEAR_ADMIN_BOOKING_MESSAGE";
export const CLEAR_ADMIN_BOOKING_ERROR="CLEAR_ADMIN_BOOKING_ERROR";