export const BUSINESS_REGISTER_REQUEST='BUSINESS_REGISTER_REQUEST';
export const BUSINESS_REGISTER_SUCCESS='BUSINESS_REGISTER_SUCCESS';
export const BUSINESS_REGISTER_FAILURE='BUSINESS_REGISTER_FAILURE';

export const BUSINESS_UPDATE_REQUEST='BUSINESS_UPDATE_REQUEST';
export const BUSINESS_UPDATE_SUCCESS='BUSINESS_UPDATE_SUCCESS';
export const BUSINESS_UPDATE_FAILURE='BUSINESS_UPDATE_FAILURE';

export const BUSINESS_REMOVE_REQUEST='BUSINESS_REMOVE_REQUEST';
export const BUSINESS_REMOVE_SUCCESS='BUSINESS_REMOVE_SUCCESS';
export const BUSINESS_REMOVE_FAILURE='BUSINESS_REMOVE_FAILURE';

export const BUSINESS_GET_BY_ID_REQUEST = 'BUSINESS_GET_BY_ID_REQUEST';
export const BUSINESS_GET_BY_ID_SUCCESS = 'BUSINESS_GET_BY_ID_SUCCESS';
export const BUSINESS_GET_BY_ID_FAILURE = 'BUSINESS_GET_BY_ID_FAILURE';


