export const JOB_REGISTER_REQUEST = 'JOB_REGISTER_REQUEST';
export const JOB_REGISTER_SUCCESS = 'JOB_REGISTER_SUCCESS';
export const JOB_REGISTER_FAILURE = 'JOB_REGISTER_FAILURE';

export const JOB_UPDATE_REQUEST = 'JOB_UPDATE_REQUEST';
export const JOB_UPDATE_SUCCESS = 'JOB_UPDATE_SUCCESS';
export const JOB_UPDATE_FAILURE = 'JOB_UPDATE_FAILURE';

export const JOB_REMOVE_REQUEST = 'JOB_REMOVE_REQUEST';
export const JOB_REMOVE_SUCCESS = 'JOB_REMOVE_SUCCESS';
export const JOB_REMOVE_FAILURE = 'JOB_REMOVE_FAILURE';

export const JOB_GET_BY_ID_REQUEST = 'JOB_GET_BY_ID_REQUEST';
export const JOB_GET_BY_ID_SUCCESS = 'JOB_GET_BY_ID_SUCCESS';
export const JOB_GET_BY_ID_FAILURE = 'JOB_GET_BY_ID_FAILURE';



export const GET_ALL_JOB_REQUEST = 'GET_ALL_JOB_REQUEST';
export const GET_ALL_JOB_SUCCESS = 'GET_ALL_JOB_SUCCESS';
export const GET_ALL_JOB_FAILURE = 'GET_ALL_JOB_FAILURE';

