export const SERVICE_REGISTER_REQUEST='SERVICE_REGISTER_REQUEST';
export const SERVICE_REGISTER_SUCCESS='SERVICE_REGISTER_SUCCESS';
export const SERVICE_REGISTER_FAILURE='SERVICE_REGISTER_FAILURE';


    
    
export const SERVICE_UPDATE_REQUEST='SERVICE_UPDATE_REQUEST';
export const SERVICE_UPDATE_SUCCESS='SERVICE_UPDATE_SUCCESS';
export const SERVICE_UPDATE_FAILURE='SERVICE_UPDATE_FAILURE';

export const SERVICE_REMOVE_REQUEST = 'SERVICE_REMOVE_REQUEST';
export const SERVICE_REMOVE_SUCCESS = 'SERVICE_REMOVE_SUCCESS';
export const SERVICE_REMOVE_FAILURE = 'SERVICE_REMOVE_FAILURE';


export const SERVICE_GET_BY_ID_REQUEST = 'SERVICE_GET_BY_ID_REQUEST';
export const SERVICE_GET_BY_ID_SUCCESS = 'SERVICE_GET_BY_ID_SUCCESS';
export const SERVICE_GET_BY_ID_FAILURE = 'SERVICE_GET_BY_ID_FAILURE';

export const GET_ALL_SERVICE_REQUEST = 'GET_ALL_SERVICE_REQUEST';
export const GET_ALL_SERVICE_SUCCESS = 'GET_ALL_SERVICE_SUCCESS';
export const GET_ALL_SERVICE_FAILURE = 'GET_ALL_SERVICE_FAILURE';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';
