export const SERVICE_BOOKING_CREATE_REQUEST = 'SERVICE_BOOKING_CREATE_REQUEST';
export const SERVICE_BOOKING_CREATE_SUCCESS = 'SERVICE_BOOKING_CREATE_SUCCESS';
export const SERVICE_BOOKING_CREATE_FAILURE = 'SERVICE_BOOKING_CREATE_FAILURE';

export const GET_MY_BOOKINGS_REQUEST = "GET_MY_BOOKINGS_REQUEST";
export const GET_MY_BOOKINGS_SUCCESS = "GET_MY_BOOKINGS_SUCCESS";
export const GET_MY_BOOKINGS_FAILURE = "GET_MY_BOOKINGS_FAILURE";

export const GET_PROVIDER_BOOKINGS_REQUEST = "GET_PROVIDER_BOOKINGS_REQUEST";
export const GET_PROVIDER_BOOKINGS_SUCCESS = "GET_PROVIDER_BOOKINGS_SUCCESS";
export const GET_PROVIDER_BOOKINGS_FAILURE = "GET_PROVIDER_BOOKINGS_FAILURE";

export const SEND_COMPLETION_OTP_REQUEST = "SEND_COMPLETION_OTP_REQUEST";
export const SEND_COMPLETION_OTP_SUCCESS = "SEND_COMPLETION_OTP_SUCCESS";
export const SEND_COMPLETION_OTP_FAILURE = "SEND_COMPLETION_OTP_FAILURE";

export const VERIFY_COMPLETION_OTP_REQUEST = "VERIFY_COMPLETION_OTP_REQUEST";
export const VERIFY_COMPLETION_OTP_SUCCESS = "VERIFY_COMPLETION_OTP_SUCCESS";
export const VERIFY_COMPLETION_OTP_FAILURE = "VERIFY_COMPLETION_OTP_FAILURE";

export const CLEAR_SERVICE_MESSAGE = "CLEAR_SERVICE_MESSAGE";
export const CLEAR_SERVICE_ERROR="CLEAR_SERVICE_ERROR";

export const PROVIDER_CANCEL_BOOKING_REQUEST = "PROVIDER_CANCEL_BOOKING_REQUEST";
export const PROVIDER_CANCEL_BOOKING_SUCCESS = "PROVIDER_CANCEL_BOOKING_SUCCESS";
export const PROVIDER_CANCEL_BOOKING_FAILURE = "PROVIDER_CANCEL_BOOKING_FAILURE";

export const SEEKER_CANCEL_BOOKING_REQUEST = "SEEKER_CANCEL_BOOKING_REQUEST";
export const SEEKER_CANCEL_BOOKING_SUCCESS = "SEEKER_CANCEL_BOOKING_SUCCESS";
export const SEEKER_CANCEL_BOOKING_FAILURE = "SEEKER_CANCEL_BOOKING_FAILURE";

